### ISSUE TITLE
Matching Option question - incorrect display when matching text has no answer option text

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Plugins/fielocms-fieloelr#10]
In the Matching Option question type, it's possible to have an answer option where the matching option has no corresponding answer option text.
![image](https://user-images.githubusercontent.com/26011197/28623122-bf39517e-71eb-11e7-919a-f0c68215c9b3.png)
In this case, all the matching option texts should be displayed for each existent answer option text.  As we can see below, there is an extra line displayed as "undefined" that should not be displayed.
![image](https://user-images.githubusercontent.com/26011197/28623408-4f12e986-71ec-11e7-8a60-3655fb6f6b0f.png)

**Comment by tibeal** [comment]
Fixed. :ok_hand:

Thanks.
