### ISSUE TITLE
Module does not complete when member fails the question for all allowed attempts

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Plugins/fielocms-fieloelr#14]
If the member doesn't answer correctly the last question, after trying all the allowed attempts, the module does not finish and the page remains loading indefinitely.
![image](https://user-images.githubusercontent.com/26011197/28718351-dda1b304-737b-11e7-8f54-bb1511986e4f.png)

**Comment by tibeal** [comment]
Fixed! 👍
