### ISSUE TITLE
"Take" button is displayed for module with dependencies in a course with Subscription Mode = Automatic

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Plugins/fielocms-fieloelr#15]
When the course has the subscription mode set to "Automatic", any of the modules can be taken by the member, unless it has dependencies.
For courses set with this subscription mode, the take button is displayed for the modules that have dependencies and when clicked no message is displayed. 
Since this button is not displayed for modules with dependencies belonging to courses with SM = Manual, they should not be displayed for modules with dependencies belonging to courses with SM= Automatic either.

**Comment by mfernandagf** [comment]
Probably the the logic to display the button is reversed, since after being approved in the predecessor module, the "Take" button of the next module has disappeared.
The subscription mode for the course was Automatic.

**Comment by tibeal** [comment]
Fixed.

There were some issues on the API. We just fixed it on version 1.16.

Thanks! 👍
