### ISSUE TITLE
Module Response is not being submitted

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Plugins/fielocms-fieloelr#17]
After ending the module giving all the correct answers, the module response informs no grade and sets Is Approved to "false".
![image](https://user-images.githubusercontent.com/26011197/28847085-5c4c0c84-76e4-11e7-91fb-a0154af94e81.png)
The module response is not being submitted:
![image](https://user-images.githubusercontent.com/26011197/28847137-915958b4-76e4-11e7-91cc-0acd2c21b9e9.png)

**Comment by tibeal** [comment]
It's an PLT issue. :argentina: Engineering is helping us to solve this.

**Comment by tibeal** [comment]
Fixed.

The :argentina: Engineering helped us with some guidelines. There were some procedures and workarounds to fix it.
