### ISSUE TITLE
View button doesn't show the last module response info after the last attempt of the module

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Plugins/fielocms-fieloelr#18]
In the example below, the module had 2 attempts allowed. After taking the second attempt and going back to the course detail page, when pressing the View button, the system shows the Module page (as if the member would take the module again) and not the last Module response page.
![image](https://user-images.githubusercontent.com/26011197/28878967-36505cfe-7777-11e7-95e7-790e52196681.png)
![image](https://user-images.githubusercontent.com/26011197/28879005-4e949eba-7777-11e7-9a50-44638177ad0a.png)

**Comment by tibeal** [comment]
Fixed. 👍
