### ISSUE TITLE
Module Response Detail - Partial Grade Value only takes into account the last question attempt

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Plugins/fielocms-fieloelr#20]
In the Module Response detail page, the partial grade value displayed is the one that was given to the last attempt of the question.  This may cause the member the feeling that he succeeded the module with a grade greater than the real one.
![image](https://user-images.githubusercontent.com/26011197/28889185-9cc7a84e-7799-11e7-9a7a-38835084ef88.png)

**Comment by tibeal** [comment]
This should be fixed by the latest release of **FieloELR** **package**.
