### ISSUE TITLE
Matching Options - Question response does not display the correct answers when question is correct but the module was not approved.

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Plugins/fielocms-fieloelr#21]
It doesn't matter if the member was approved or not on the module, if he correctly  replied the "Matching Options" question, the question response should show his correct answers.
![image](https://user-images.githubusercontent.com/26011197/28980257-8b1741aa-7923-11e7-8334-19b70b9deade.png)

**Comment by tibeal** [comment]
This should be fixed by the latest release of the **FieloELR package**.
