### ISSUE TITLE
Short Answer - Question response does not display the correct answers when question is correct but the module was not approved.

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Plugins/fielocms-fieloelr#22]
It doesn't matter if the member was approved or not on the module, if he correctly replied the "Short Answer" question, the question response should show the answer options.
![image](https://user-images.githubusercontent.com/26011197/28980581-bedfd000-7924-11e7-8ca6-fb562a26c7bd.png)

**Comment by tibeal** [comment]
This should be fixed by the latest release of the **FieloELR package**.
