### ISSUE TITLE
Short Answer - Before module approval, question response displays no info for an incorrect answer

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Plugins/fielocms-fieloelr#23]
While member does not approve the module, every time he incorrectly replies a "Short Answer" question, he should see, at least, the *Incorrect* status for this question.
![image](https://user-images.githubusercontent.com/26011197/28981579-abd2e732-7928-11e7-8812-d4ec9fa5ef53.png)

**Comment by tibeal** [comment]
This should be fixed by the latest release of the **FieloELR package**.
