### ISSUE TITLE
Retake button not displayed when module "Attempts allowed" is unlimited

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Plugins/fielocms-fieloelr#4]
The module below has no limit for the attempts allowed, but the retake button is not displayed:
![image](https://user-images.githubusercontent.com/26011197/28423360-3372660c-6d41-11e7-99df-4afd4b939bb4.png)
![image](https://user-images.githubusercontent.com/26011197/28423415-534b8b8e-6d41-11e7-8179-cbd7f849be99.png)

**Comment by tibeal** [comment]
Fixed! 👍
