### ISSUE TITLE
"Take" and "Retake" buttons should not be displayed in "My Courses" for a scheduled course

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Plugins/fielocms-fieloelr#45]

**Comment by mfernandagf** [comment]
Consider that a member has already taken some modules of an active course. In this case, this course appears in "My Courses" page, since the member has already started the course.
Suppose that this course had its dates changed and, when reactivated, it changed its status to Scheduled.
When the member goes again to "My Courses" page, the buttons "Take" and "Retake" are still being displayed, but when pressed, nothing happens.
They should not be diplayed. Only the "View" button should be displayed for the modules already taken.

**Comment by tibeal** [comment]
Fixed in the ELR Plugin Org
