### ISSUE TITLE
Single Question cannot be answered correctly after failing

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Plugins/fielocms-fieloelr#5]
When the attempts allowed per question are unlimited or greater than 1, if the member the fails an attempt and tries to answer correctly in the next attempt, it's not possible to "reset" the answer option choosen previously, which makes him fail again.
In the example below, the member chose the second option and submitted the question. In his second attempt, he chose the first option, but he could not uncheck the second option.
The same happens for Statement questions.
![image](https://user-images.githubusercontent.com/26011197/28529439-ee165612-7066-11e7-8661-948a6d8ded33.png)

**Comment by tibeal** [comment]
Fixed! 👌
