### ISSUE TITLE
Inactive modules are being displayed for the course

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Plugins/fielocms-fieloelr#53]
In the image below, the second module is inactive and should not be displayed.
COURSE NAME: New Course
![image](https://user-images.githubusercontent.com/26011197/30502052-199cf0e0-9a3b-11e7-846f-915deef0a23c.png)
![image](https://user-images.githubusercontent.com/26011197/30502108-4a6fce90-9a3b-11e7-868a-8aca062d471e.png)

**Comment by tibeal** [comment]
@mfernandagf 

In the plugin, now we do not show any possible action for the module.

The remaining issue will be treated by the FieloELR repo. The module should not appear in the list.

_**Best Regards**_
