### ISSUE TITLE
Matching Options - Question response does not display "Your answer" when question is incorrect

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Plugins/fielocms-fieloelr#72]
![image](https://user-images.githubusercontent.com/26011197/31351121-4240d6b0-ad00-11e7-8210-9f2fd27aad4c.png)

![image](https://user-images.githubusercontent.com/26011197/31351144-578455e2-ad00-11e7-9548-e3a2d0c31862.png)

**Comment by tibeal** [comment]
This should be fixed in the latest release of the **FieloELR package**.
