### ISSUE TITLE
Change label in Module Response page

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Plugins/fielocms-fieloelr#74]
Change label "Is Approved" to "Passed" as done in the course modules list and its the respective icons.
![image](https://user-images.githubusercontent.com/26011197/31354535-1ef7b05e-ad0d-11e7-9f49-30dfbcf291d2.png)

**Comment by tibeal** [comment]
This should be fixed by the latest release of the **FieloELR package**.
