### ISSUE TITLE
Question text supports only 162 characters

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Plugins/fielocms-fieloelr#8]
Some question texts may be long, but when trying to display a real question (extracted from the web) the text was not displayed. Only after reducing it to 162 characteres, the text was able to be displayed.
Question text reduced to 162 characters:
![image](https://user-images.githubusercontent.com/26011197/28575859-8fd39322-7128-11e7-8902-dc08590db881.png)
Complete question text:
![image](https://user-images.githubusercontent.com/26011197/28576084-36de27f4-7129-11e7-813b-b8ced62770a8.png)

**Comment by mfernandagf** [comment]
In fact, it does not seem to be a character quantity issue, as after reducing the question text to 162 characters and confirming it was displayed in the page, another question was inserted in the module and the first one that was ok disappeared.
Also, after including one more matching option to a question, the module didn't display any questions at all. Please, verify this last issue on "Test Module 1" of "Test Course".

**Comment by tibeal** [comment]
It seems to be fixed. Can you check that @mfernandagf ?

This is a 313 character long question text:
![screenhunter_01 jul 28 09 58](https://user-images.githubusercontent.com/7199593/28718211-5929bd2e-737b-11e7-8199-662a523157b3.gif)
